% @author: Maziar Raissi

function K_ff = k_ff(x, y, hyp,i)

logsigma = hyp(1);
logtheta = hyp(2);
alpha = hyp(3);
beta = hyp(4);

if i == 0 || i == 1
    
    kk = @(x,y) (1/2).*exp(1).^(logsigma+(-2).*logtheta+(-1/2).*exp(1).^((-1).* ...
        logtheta).*(x.^2+y.^2)).*(2.*exp(1).^(2.*logtheta+(1/2).*exp(1).^( ...
        (-1).*logtheta).*x.^2).*beta.*(1+exp(1).^logtheta.*beta)+(-2).*exp(1).^( ...
        exp(1).^((-1).*logtheta).*x.*y).*((x+(-1).*y).^2+exp(1) ...
        .^logtheta.*((-1)+exp(1).^logtheta.*((-1).*alpha.^2+beta.*(2+exp(1) ...
        .^logtheta.*beta))))+exp(1).^(2.*logtheta+(1/2).*exp(1).^((-1).* ...
        logtheta).*y.^2).*beta.*(2+2.*exp(1).^logtheta.*beta+exp(1).^((1/2).*( ...
        logtheta+exp(1).^((-1).*logtheta).*x.^2)).*((-2).*exp(1).^((1/2).* ...
        logtheta).*beta+(2.*pi).^(1/2).*((alpha+x.*beta).*erf(2.^(-1/2).*exp(1).^(( ...
        -1/2).*logtheta).*x)+((-1).*x+y).*beta.*erf(2.^(-1/2).*exp(1).^(( ...
        -1/2).*logtheta).*(x+(-1).*y))+(alpha+y.*beta).*erf(2.^(-1/2).*exp(1).^(( ...
        -1/2).*logtheta).*y)))));
    
    K_ff = bsxfun(kk,x,y');
    
elseif i==2
    
    kk = @(x,y) (1/4).*exp(1).^((-3).*logtheta+(-1/2).*exp(1).^((-1).*logtheta).* ...
        x.^2).*((-2).*exp(1).^(logsigma+(-1/2).*exp(1).^((-1).*logtheta).* ...
        y.^2).*((-1).*exp(1).^(2.*logtheta+(1/2).*exp(1).^((-1).*logtheta) ...
        .*x.^2).*beta.*(y.^2+(-1).*exp(1).^logtheta.*y.*alpha+2.*exp(1).^(2.* ...
        logtheta).*beta)+exp(1).^(exp(1).^((-1).*logtheta).*x.*y).*((-5).* ...
        exp(1).^logtheta.*(x+(-1).*y).^2+(x+(-1).*y).^4+exp(1).^(2.* ...
        logtheta).*(2+(-1).*(x+(-1).*y).^2.*(alpha.^2+(-2).*beta))+2.*exp(1).^( ...
        4.*logtheta).*beta.^2))+exp(1).^(logsigma+2.*logtheta).*beta.*(2.*x.^2+( ...
        -2).*exp(1).^logtheta.*x.*alpha+(-4).*exp(1).^(2.*logtheta).*((-1)+...
        exp(1).^((1/2).*exp(1).^((-1).*logtheta).*x.^2)).*beta+exp(1).^((1/2) ...
        .*(3.*logtheta+exp(1).^((-1).*logtheta).*x.^2)).*(2.*pi).^(1/2).*( ...
        (alpha+x.*beta).*erf(2.^(-1/2).*exp(1).^((-1/2).*logtheta).*x)+((-1).*x+ ...
        y).*beta.*erf(2.^(-1/2).*exp(1).^((-1/2).*logtheta).*(x+(-1).*y))+(alpha+ ...
        y.*beta).*erf(2.^(-1/2).*exp(1).^((-1/2).*logtheta).*y))));
    
    K_ff = bsxfun(kk,x,y');
    
elseif i==3
    kk = @(x,y) 2.*exp(1).^(logsigma+(-1/2).*exp(1).^((-1).*logtheta).*(x+(-1).*y) ...
        .^2).*alpha+exp(1).^(logsigma+(1/2).*logtheta).*((1/2).*pi).^(1/2).* ...
        beta.*(erf(2.^(-1/2).*exp(1).^((-1/2).*logtheta).*x)+erf(2.^(-1/2).* ...
        exp(1).^((-1/2).*logtheta).*y));
    
    K_ff = bsxfun(kk,x,y');
    
elseif i ==4
    kk = @(x,y) (1/2).*exp(1).^logsigma.*(2.*(exp(1).^((-1/2).*exp(1).^((-1).* ...
        logtheta).*x.^2)+(-2).*exp(1).^((-1/2).*exp(1).^((-1).*logtheta).* ...
        (x+(-1).*y).^2)+exp(1).^((-1/2).*exp(1).^((-1).*logtheta).*y.^2)+( ...
        -2).*exp(1).^logtheta.*beta+2.*exp(1).^(logtheta+(-1/2).*exp(1).^(( ...
        -1).*logtheta).*x.^2).*beta+(-2).*exp(1).^(logtheta+(-1/2).*exp(1).^( ...
        (-1).*logtheta).*(x+(-1).*y).^2).*beta+2.*exp(1).^(logtheta+(-1/2).* ...
        exp(1).^((-1).*logtheta).*y.^2).*beta)+exp(1).^((1/2).*logtheta).*( ...
        2.*pi).^(1/2).*((alpha+2.*x.*beta).*erf(2.^(-1/2).*exp(1).^((-1/2).* ...
        logtheta).*x)+2.*((-1).*x+y).*beta.*erf(2.^(-1/2).*exp(1).^((-1/2).* ...
        logtheta).*(x+(-1).*y))+(alpha+2.*y.*beta).*erf(2.^(-1/2).*exp(1).^(( ...
        -1/2).*logtheta).*y)));
    
    K_ff = bsxfun(kk,x,y');
end

end

